### ISSUE TITLE
Milestone 1 Grades

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/credit_default_prediction_group_20#32]
### 1. Project set-up (max 20 points)

- [ ] The public repository has been created in the organization UBC-MDS and all the team members are part of it. **-1** 
- [ ] The analysis notebook (`*.ipynb` or `.Rmd`) should be in a sub-directory called something sensible, such as `analysis`, `src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones. 
Having too many files in the project root makes the project organization less understandable 
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**
- [ ] Files such as `.DS_Store` should not be committed. **-1**

**Team work contract** (max 5 points)

- [ ] Team work contract missing. **-5**
- [ ] Team work contract was pushed to GitHub **-5**

**Code of Conduct.md** (5 points total)
- [ ] A procedure for reporting and dealing with unacceptable behaviour is explicitly included. In particular is important to add who to contact in case something happens.  **-2**
- [ ] A Statement on diversity and inclusivity **-1**
- [ ] A list of consequences for unacceptable behaviour **-1**
- [ ] Details on expected, and unacceptable behaviour **-1**
  
**CONTRIBUTING.md** (2 points in total)

- [ ] Contributing documentation should reflect all the ways people can contribute to the project 
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-2**

**License** (max 5 points)
- [ ] Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived. **-2**
- [ ] Software license (e.g., MIT) needs to be included to specify how non-code/software work can be used, shared and derived. **-2**
- [ ] No license was specified **-5**

### 2. Project proposal (10 points)

- [ ] The dataset, dataset license and dataset citation should be included in the README.md. **-1**
- [ ] The project should be asking a predictive or statistical question. 
See https://datasciencebook.ca/intro.html#asking-a-question and https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#revisiting-the-definition-of-data-science-what-is-the-question 
for clarification if needed. **-3** **reasoning**
- [ ] The question should be specific enough. For example, "Is eating a healthier diet better for you?" is written ambiguously. What do you mean by "healthier diet"? . Instead, "Does eating at least 5 servings per day of fresh fruits and vegetables lead to fewer upper respiratory tract infections (colds)?" is clearer and more concrete. **-1** **reasoning**
- [ ] Clarity of README could be improved through additional proofreading (i.e., spelling and grammatical errors are present). **-1**
- [ ] The proposed methodology in the README should be clearly explained, mentioning the statistical methods / models they will use (at least at a high-level). **-3** **reasoning**
- [ ] The README should include the list of authors/contributors and a title. **-1**
- [ ] The README should mention the licenses for code and text (not the dataset license only). **-1**
## 3. A script that downloads and saves the data

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-3**
- [ ] Could not reproducibly run the analysis because there is no instructions. **-3**
- [ ] The data should be reproducibly downloaded from it's source using code in the analysis code document. **-3**
- [ ] A first copy of the data must be saved in the `data` directory (and ideally in the `data/raw` subdirectory. **-1**
- [ ] The script should be documented (use of docstrings / comments) **-3** **accuracy**
- [ ] The script is placed in an appropiated subdirectory as the `src` folder **-1**
## 4. Exploratory data analysis in a literate code document
- [ ] This document should not actually be named `analysis.ipynb` or `analysis.Rmd`, but have a more descriptive title, related to the project title. **-1**
- [ ] The document contains some problem. For instance, a plot that is not rendered correctly. **-1**
- [ ] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. **-2** **viz**
- [x] #36
- [ ] There figure captions for the tables should be above the table. **-1** **viz**
- [ ] There are less than the required 2 plots and one table **-2**
- [ ] Missing a summary/abstract in the analysis (`.ipynb` or `.Rmd`) file **-2**
- [ ] There is not title, introduction and/or references in the analysis (`.ipynb` or `.Rmd`) file **-2**
- [x] #37
- [x] #38
- [ ] README should include instructions on how to run the analysis.Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) suggest the most reasonable value and provide the list (or link to a list) of alternative options. **-2**
- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2** **writing**
- [ ] The text is difficult to understand. Clarity could be improved. There are many typos, the text is difficult to read.  **-2** **writing**
- [ ] Dependencies (or link pointing to list elsewhere) is missing from the `README.md` file. The dependency list should include `docopt` package. **-2**

### Expectations
- [ ] GitHub issues were not used. **-5**
- [ ] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` 
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). 
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**
- [ ] There is no link nor instructions to access the GitHub release for milestone 1. **-2**
- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to have meaningful names to reflect the piece of work being done (not names of contributors) and should also include scope (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-1**
- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to be divided into independent units of work (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-1**
- [ ] All contributions are expected to go through code review via a pull-request. A branch protection rule should be set in the `main` branch. There shouldn't exist commits in the `main` branch, except the ones created when you merged branches. **-2**
- [ ] Branching in the core team's project repository is the expected workflow, not forking. **-1**
- [ ] All the team-members should have meaninful commits in the project **-5**
