### ISSUE TITLE
Milestone 3 Work Distribution

### ISSUE THREAD

**Issue by rkrishnan-arjun** [UBC-MDS/credit_default_prediction_group_20#43]
Arjun: 
- Reproducibility
- Proposal doc.

@kenuiuc - 
- [x] Make file
- [x] Update usage in readme
- [x] Altair is not used. Correct fig 4.
- [x] Add confusion matrix for RFC.
- [x] Add appropriate titles and syntax.

@mozhao0331 -
- Address milestone 1 issues. 

@Althrun-sun -
- EDA: Altair is not used.
- Better Fig 1.
